### ISSUE TITLE
[Request] Left sidebar theme should be consistent with the right sidebar

### ISSUE THREAD

**Issue by robmonte** [pygaurav/vasuki-dark-vscode-theme#1]
In my right sidebar where my terminal and debug console are, the section titles have a gray background to differentiate each from the background of the panel. Secondly, there is a light-colored vertical line separating the right sidebar from the editor. You can see both of these in the below screenshot:
![image](https://user-images.githubusercontent.com/17119716/186074963-f0225c53-12dc-4f0e-869c-e96d58a066e6.png)

&nbsp;

However, the left sidebar lacks both the gray section title background color and the vertical line separating it from the editor. You can see both of these missing in this next screenshot:
![image](https://user-images.githubusercontent.com/17119716/186075309-8e8b1735-e6ab-43d4-a590-f357ccea99e4.png)

**Comment by pygaurav** [comment]
@robmonte Thanks for spotting a nice catch, theme has been updated. The colors consistency is increased now. You can update to the latest `v1.0.4`

**Comment by robmonte** [comment]
Thanks for updating @pygaurav! The border between the left sidebar and the editor looks great. 👍

I actually think the theme might be better if the _opposite_ change was made to the headers. If the section header background colors are lighter than the background I believe it improves recognition.

If these two values are set to the same color as the highlight color of a selected file in the explorer:
```
"sideBarSectionHeader.background": "#141821",
"panelSectionHeader.background": "#141821",
```

This change would look like this:
![image](https://user-images.githubusercontent.com/17119716/186235143-26ae75dd-f5c5-47c3-8db9-1a99f69057f6.png)

Let me know what you think!

**Comment by pygaurav** [comment]
Thanks for bringing your nice idea's. I was already working upon the unified theming approach. PR #2  is now opened. You can have a look. I am currently testing that considering all cases, if it looks good then will merge it and will release a newer version.
