### ISSUE TITLE
[Request] Border on the resizeable part should not disappear

### ISSUE THREAD

**Issue by rokimiftah** [pygaurav/vasuki-dark-vscode-theme#3]
When I want to change the width of the sidebar, I can't see how far the line I'm touching is. So the border should not disappear.
![disappear](https://user-images.githubusercontent.com/32923249/187073652-47515937-9ee8-4aa0-970a-6f54c3cf2d51.gif)

**Comment by pygaurav** [comment]
@rokimiftah Thanks for the bug, [PR#4](https://github.com/pygaurav/vasuki-dark-vscode-theme/pull/4) is merged. v1.0.7 has been rolled out. You can update the theme.
